version: '3'
services:
  my-frontend:
    build: ./my-frontend
    ports:
      - "3000:3000"

  my-backend:
    build: ./my-backend
    ports:
      - "3001:3001"

  my-database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: my-database
      PMA_PORT: 3306

