version: '3'
services:
  my-frontend:
    build: ./my-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=  http://my-backend:3001

  my-backend:
    build: ./my-backend
    ports:
      - "3001:3001"
    depends_on:
      - my-database

  my-database:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_HOST=my-database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my_database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: my-database
      PMA_PORT: 3306

volumes:  
  db_data: {}